# Generated by Django 3.2 on 2021-06-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Get_started',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=30)),
                ('email_user', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, max_length=350, null=True)),
                ('sending_time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
