# Generated by Django 3.2 on 2021-06-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='get_started',
            options={'verbose_name': 'Заявка на сотрудничество', 'verbose_name_plural': 'Заявки на сотрудничество'},
        ),
        migrations.AlterField(
            model_name='get_started',
            name='email_user',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='get_started',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='get_started',
            name='name_user',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='get_started',
            name='sending_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Sending Time'),
        ),
    ]
